### ISSUE TITLE
Create contractor saga

### ISSUE THREAD

**Issue by ChrisCantoni** [8bitcoffee/borderless-translations#20]
Create a reducer to fetch list of contractors for AdminContractorPage. Dispatch type 'FETCH_CONTRACTORS' to be stored in redux as 'contractors'

**Comment by 8bitcoffee** [comment]
Needs confirmation of URL

**Comment by 8bitcoffee** [comment]
Needs URL confirmation. Names were changed to match others

saga dispatch type is "GET_ALL_CONTRACTORS"
stored in redux in the reducer 'allContractors'
