### ISSUE TITLE
Create contractor details saga

### ISSUE THREAD

**Issue by ChrisCantoni** [8bitcoffee/borderless-translations#21]
Create a reducer to fetch specific contractor details. Dispatch type 'FETCH_CONTRACTOR_DETAILS' payload to be that contractor's ID. To be stored in redux as 'contractorDetails'

**Comment by 8bitcoffee** [comment]
Needs URL confirmation. Names were changed to match others

saga dispatch type is "GET_CONTRACTOR"
stored in redux in the reducer 'contractor'
