### ISSUE TITLE
Create a reducer to fetch list of projects for AdminProjectPage. Dispatch type: 'FETCH_PROJECTS' to be stored in redux as 'projects'.

### ISSUE THREAD

**Issue by Juan-Balbuena** [8bitcoffee/borderless-translations#23]

**Comment by 8bitcoffee** [comment]
Created reducer and saga to fetch all projects. Name was changed slightly to conform to other names. URL connecting it to router needs to be confirmed

type: "GET_ALL_PROJECTS"
reducer: allProjects
